# Generated by Django 5.1.2 on 2024-11-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_temperaturesensor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date_of_measurement',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.temperaturesensor'),
        ),
    ]
