# Generated by Django 5.1.2 on 2024-11-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_sensordata_date_of_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sensor_images/'),
        ),
    ]
